version: '3.9'

services:
  web:
    build:
      context: .
    container_name: web
    image: core:latest
    restart: always
    command: >
      sh -c 'python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000'
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis_data:/data
    env_file:
      - .env
    ports:
      - "6380:6379"

volumes:
  postgres_data:
  redis_data: