from django.core.management.base import BaseCommand
from apps.ecom.models import Attribute, AttributeValue

class Command(BaseCommand):
    help = 'Populate common colors and their associated color codes'

    def handle(self, *args, **kwargs):
        colors_and_codes = {
            'Absolute Zero': '#0048BA',
            'Acid Green': '#B0BF1A',
            'Aero': '#7CB9E8',
            'Aero Blue': '#C9FFE5',
            'African Violet': '#B284BE',
            'Air Force Blue (RAF)': '#5D8AA8',
            'Air Force Blue (USAF)': '#00308F',
            'Air Superiority Blue': '#72A0C1',
            'Alabama Crimson': '#AF002A',
            'Alabaster': '#F2F0E6',
            'Alice Blue': '#F0F8FF',
            'Alloy Orange': '#C46210',
            'Almond': '#EFDECD',
            'Amaranth': '#E52B50',
            'Amaranth Pink': '#F19CBB',
            'Amazon': '#3B7A57',
            'Amber': '#FFBF00',
            'American Rose': '#FF033E',
            'Amethyst': '#9966CC',
            'Android Green': '#A4C639',
            'Antique Brass': '#CD9575',
            'Antique Bronze': '#665D1E',
            'Antique Fuchsia': '#915C83',
            'Antique Ruby': '#841B2D',
            'Antique White': '#FAEBD7',
            'Ao (English)': '#008000',
            'Apple Green': '#8DB600',
            'Apricot': '#FBCEB1',
            'Aqua': '#00FFFF',
            'Aquamarine': '#7FFFD4',
            'Army Green': '#4B5320',
            'Arsenic': '#3B444B',
            'Arylide Yellow': '#E9D66B',
            'Ash Grey': '#B2BEB5',
            'Asparagus': '#87A96B',
            'Atomic Tangerine': '#FF9966',
            'Auburn': '#A52A2A',
            'Aureolin': '#FDEE00',
            'Avocado': '#568203',
            'Azure': '#007FFF',
            'Baby Blue': '#89CFF0',
            'Baby Blue Eyes': '#A1CAF1',
            'Baby Pink': '#F4C2C2',
            'Baby Powder': '#FEFEFA',
            'Baker-Miller Pink': '#FF91AF',
            'Ball Blue': '#21ABCD',
            'Banana Mania': '#FAE7B5',
            'Banana Yellow': '#FFE135',
            'Barbie Pink': '#E0218A',
            'Barn Red': '#7C0A02',
            'Battleship Grey': '#848482',
            'Beau Blue': '#BCD4E6',
            'Beaver': '#9F8170',
            'Beige': '#F5F5DC',
            'B\'dazzled Blue': '#2E5894',
            'Bisque': '#FFE4C4',
            'Bistre': '#3D2B1F',
            'Bitter Lemon': '#CAE00D',
            'Bitter Lime': '#BFFF00',
            'Bittersweet': '#FE6F5E',
            'Black': '#000000',
            'Black Bean': '#3D0C02',
            'Black Olive': '#3B3C36',
            'Blanched Almond': '#FFEBCD',
            'Blast-Off Bronze': '#A57164',
            'Bleu De France': '#318CE7',
            'Blizzard Blue': '#ACE5EE',
            'Blond': '#FAF0BE',
            'Blue': '#0000FF',
            'Blue Bell': '#A2A2D0',
            'Blue-Gray': '#6699CC',
            'Blue-Green': '#0D98BA',
            'Blue Sapphire': '#126180',
            'Blue-Violet': '#8A2BE2',
            'Blush': '#DE5D83',
            'Bole': '#79443B',
            'Bondi Blue': '#0095B6',
            'Bone': '#E3DAC9',
            'Boston University Red': '#CC0000',
            'Brandeis Blue': '#0070FF',
            'Brass': '#B5A642',
            'Brick Red': '#CB4154',
            'Bright Cerulean': '#1DACD6',
            'Bright Green': '#66FF00',
            'Bright Pink': '#FF007F',
            'Bright Turquoise': '#08E8DE',
            'Brilliant Rose': '#FF55A3',
            'Brink Pink': '#FB607F',
            'British Racing Green': '#004225',
            'Bronze': '#CD7F32',
            'Brown': '#964B00',
            'Bubble Gum': '#FFC1CC',
            'Burgundy': '#800020',
            'Burlywood': '#DEB887',
            'Burnt Orange': '#CC5500',
            'Burnt Sienna': '#E97451',
            'Burnt Umber': '#8A3324',
            'Byzantine': '#BD33A4',
            'Byzantium': '#702963',
            'Cadet': '#536872',
            'Cadet Blue': '#5F9EA0',
            'Cadet Grey': '#91A3B0',
            'Cadmium Green': '#006B3C',
            'Cadmium Orange': '#ED872D',
            'Cadmium Red': '#E30022',
            'Cadmium Yellow': '#FFF600',
            'Camel': '#C19A6B',
            'Camouflage Green': '#78866B',
            'Canary Yellow': '#FFEF00',
            'Candy Apple Red': '#FF0800',
            'Candy Pink': '#E4717A',
            'Capri': '#00BFFF',
            'Cardinal': '#C41E3A',
            'Carmine': '#960018',
            'Carnation Pink': '#FFA6C9',
            'Carolina Blue': '#56A0D3',
            'Carrot Orange': '#ED9121',
            'Castleton Green': '#00563F',
            'Catawba': '#703642',
            'Cedar Chest': '#C95A49',
            'Celadon': '#ACE1AF',
            'Celeste': '#B2FFFF',
            'Cerise': '#DE3163',
            'Cerulean': '#007BA7',
            'Cerulean Blue': '#2A52BE',
            'Champagne': '#F7E7CE',
            'Charcoal': '#36454F',
            'Chartreuse (Web)': '#7FFF00',
            'Cherry Blossom Pink': '#FFB7C5',
            'Chestnut': '#954535',
            'Chocolate': '#7B3F00',
            'Chrome Yellow': '#FFA700',
            'Cinereous': '#98817B',
            'Cinnabar': '#E34234',
            'Citrine': '#E4D00A',
            'Citron': '#9FA91F',
            'Claret': '#7F1734',
            'Cobalt Blue': '#0047AB',
            'Cocoa Brown': '#D2691E',
            'Coffee': '#6F4E37',
            'Columbia Blue': '#C4D8E2',
            'Cool Black': '#002E63',
            'Cool Grey': '#8C92AC',
            'Copper': '#B87333',
            'Copper Rose': '#996666',
            'Coral': '#FF7F50',
            'Coral Pink': '#F88379',
            'Cordovan': '#893F45',
            'Cornflower Blue': '#6495ED',
            'Cornsilk': '#FFF8DC',
            'Cosmic Latte': '#FFF8E7',
            'Cream': '#FFFDD0',
            'Crimson': '#DC143C',
            'Cyan': '#00FFFF',
            'Daffodil': '#FFFF31',
            'Dandelion': '#F0E130',
            'Dark Blue': '#00008B',
            'Dark Brown': '#654321',
            'Dark Cyan': '#008B8B',
            'Dark Goldenrod': '#B8860B',
            'Dark Gray': '#A9A9A9',
            'Dark Green': '#013220',
            'Dark Khaki': '#BDB76B',
            'Dark Magenta': '#8B008B',
            'Dark Olive Green': '#556B2F',
            'Dark Orange': '#FF8C00',
            'Dark Orchid': '#9932CC',
            'Dark Red': '#8B0000',
            'Dark Salmon': '#E9967A',
            'Dark Sea Green': '#8FBC8F',
            'Dark Slate Blue': '#483D8B',
            'Dark Slate Gray': '#2F4F4F',
            'Dark Turquoise': '#00CED1',
            'Dark Violet': '#9400D3',
            'Deep Pink': '#FF1493',
            'Deep Sky Blue': '#00BFFF',
            'Denim': '#1560BD',
            'Desert Sand': '#EDC9AF',
            'Dodger Blue': '#1E90FF',
            'Emerald': '#50C878',
            'Eggplant': '#614051',
            'Electric Blue': '#7DF9FF',
            'Electric Green': '#00FF00',
            'Electric Indigo': '#6F00FF',
            'Electric Lime': '#CCFF00',
            'Electric Purple': '#BF00FF',
            'English Lavender': '#B48395',
            'Falu Red': '#801818',
            'Fern Green': '#4F7942',
            'Firebrick': '#B22222',
            'Flame': '#E25822',
            'Flamingo Pink': '#FC8EAC',
            'Floral White': '#FFFAF0',
            'Forest Green (Web)': '#228B22',
            'French Rose': '#F64A8A',
            'Fuchsia': '#FF00FF',
            'Gainsboro': '#DCDCDC',
            'Gamboge': '#E49B0F',
            'Ghost White': '#F8F8FF',
            'Gold': '#FFD700',
            'Goldenrod': '#DAA520',
            'Gray': '#808080',
            'Green': '#008000',
            'Green Yellow': '#ADFF2F',
            'Honeydew': '#F0FFF0',
            'Hot Pink': '#FF69B4',
            'Indian Red': '#CD5C5C',
            'Indigo': '#4B0082',
            'Ivory': '#FFFFF0',
            'Jade': '#00A86B',
            'Khaki': '#F0E68C',
            'Lavender': '#E6E6FA',
            'Lavender Blush': '#FFF0F5',
            'Lawn Green': '#7CFC00',
            'Lemon': '#FFF700',
            'Lemon Chiffon': '#FFFACD',
            'Light Blue': '#ADD8E6',
            'Light Coral': '#F08080',
            'Light Cyan': '#E0FFFF',
            'Light Goldenrod Yellow': '#FAFAD2',
            'Light Gray': '#D3D3D3',
            'Light Green': '#90EE90',
            'Light Pink': '#FFB6C1',
            'Light Salmon': '#FFA07A',
            'Light Sea Green': '#20B2AA',
            'Light Sky Blue': '#87CEFA',
            'Light Slate Gray': '#778899',
            'Light Steel Blue': '#B0C4DE',
            'Light Yellow': '#FFFFE0',
            'Lime': '#00FF00',
            'Lime Green': '#32CD32',
            'Linen': '#FAF0E6',
            'Magenta': '#FF00FF',
            'Maroon': '#800000',
            'Medium Aquamarine': '#66CDAA',
            'Medium Blue': '#0000CD',
            'Medium Orchid': '#BA55D3',
            'Medium Purple': '#9370DB',
            'Medium Sea Green': '#3CB371',
            'Medium Slate Blue': '#7B68EE',
            'Medium Spring Green': '#00FA9A',
            'Medium Turquoise': '#48D1CC',
            'Medium Violet Red': '#C71585',
            'Midnight Blue': '#191970',
            'Mint Cream': '#F5FFFA',
            'Misty Rose': '#FFE4E1',
            'Moccasin': '#FFE4B5',
            'Navajo White': '#FFDEAD',
            'Navy': '#000080',
            'Old Lace': '#FDF5E6',
            'Olive': '#808000',
            'Olive Drab': '#6B8E23',
            'Orange': '#FFA500',
            'Orange Red': '#FF4500',
            'Orchid': '#DA70D6',
            'Pale Goldenrod': '#EEE8AA',
            'Pale Green': '#98FB98',
            'Pale Turquoise': '#AFEEEE',
            'Pale Violet Red': '#DB7093',
            'Papaya Whip': '#FFEFD5',
            'Peach Puff': '#FFDAB9',
            'Peru': '#CD853F',
            'Pink': '#FFC0CB',
            'Plum': '#DDA0DD',
            'Powder Blue': '#B0E0E6',
            'Purple': '#800080',
            'Rebecca Purple': '#663399',
            'Red': '#FF0000',
            'Rosy Brown': '#BC8F8F',
            'Royal Blue': '#4169E1',
            'Saddle Brown': '#8B4513',
            'Salmon': '#FA8072',
            'Sandy Brown': '#F4A460',
            'Sea Green': '#2E8B57',
            'Seashell': '#FFF5EE',
            'Sienna': '#A0522D',
            'Silver': '#C0C0C0',
            'Sky Blue': '#87CEEB',
            'Slate Blue': '#6A5ACD',
            'Slate Gray': '#708090',
            'Snow': '#FFFAFA',
            'Spring Green': '#00FF7F',
            'Steel Blue': '#4682B4',
            'Tan': '#D2B48C',
            'Teal': '#008080',
            'Thistle': '#D8BFD8',
            'Tomato': '#FF6347',
            'Turquoise': '#40E0D0',
            'Violet': '#EE82EE',
            'Wheat': '#F5DEB3',
            'White': '#FFFFFF',
            'White Smoke': '#F5F5F5',
            'Yellow': '#FFFF00',
            'Yellow Green': '#9ACD32',
        }


        # Create or get the Color attribute
        color_attribute, created = Attribute.objects.get_or_create(name='Color')
        if created:
            self.stdout.write(self.style.SUCCESS('Attribute "Color" created'))
        else:
            self.stdout.write(self.style.WARNING('Attribute "Color" already exists'))

        # Create associated AttributeValues
        for color_name, color_code in colors_and_codes.items():
            attribute_value, value_created = AttributeValue.objects.get_or_create(attribute=color_attribute, value=color_name, color_code=color_code)
            if value_created:
                self.stdout.write(self.style.SUCCESS(f'  - Value "{color_name}" (Code: {color_code}) for attribute "Color" created'))
            else:
                self.stdout.write(self.style.WARNING(f'  - Value "{color_name}" (Code: {color_code}) for attribute "Color" already exists'))

        self.stdout.write(self.style.SUCCESS('Finished populating common colors.'))
